### ISSUE TITLE
Read-Me Correction

### ISSUE THREAD

**Issue by TwisterMc** [safak45xx/Blurfox-MacOS-#1]
In the read me it says to enable a bunch of Firefox settings, however `gfx.webrender.enabled` isn't something you can enable. it's an option you can change; `Boolean` `Number` `String`

**Comment by safak45xx** [comment]
buddy it's only been 10 minutes since I opened the page, how did you find this place so quickly :D

**Comment by safak45xx** [comment]
Boolean- true

**Comment by TwisterMc** [comment]
I just searched GitHub. 😄 I'm eager to test this, and have already completed all the steps I could.

**Comment by TwisterMc** [comment]
Also, I see how to change that to true now. It's not as obvious as all the rest. I had to hit the little weird arrow like icon, then it changed to `true` or `false`

**Comment by safak45xx** [comment]
I don't know exactly what that setting changes, but if you want, it can stay off. I didn't see any issues with the theme when that setting was off.

**Comment by TwisterMc** [comment]
I guess a screenshot would be helpful.

![Screen Shot 2024-02-19 at 8 55 08 AM](https://github.com/safak45xx/Blurfox-MacOS-/assets/46997/ca47bcf9-9e09-4079-acf3-fc508b74c30b)

Turns out I had to hit the + to get it to switch to true/false options.

**Comment by safak45xx** [comment]
yes

**Comment by safak45xx** [comment]
+ true

**Comment by safak45xx** [comment]
Please let me know how it looks, this is my first GitHub share and I'm very new to this

**Comment by TwisterMc** [comment]
It's not going to be perfect, and it doesn't have to be.

**Comment by TwisterMc** [comment]
Let me know when you post it, or if you want me to try it before you post it, we can connect.

**Comment by safak45xx** [comment]
I have just released a version now.
