### ISSUE TITLE
New Tab Button 

### ISSUE THREAD

**Issue by depleur** [safak45xx/Blurfox-MacOS-#13]
![CleanShot 2024-03-13 at 12 14 28@2x](https://github.com/safak45xx/Blurfox-MacOS-/assets/89105989/78599e44-c95c-452f-8c31-e728c740e725)
As can be seen in the attached screenshot, the add new tab button overlaps with the addons button when more than a few tabs are open. Can something be done to address this bug?

**Comment by depleur** [comment]
I'm running MacOS Sonoma 14.4. Firefox Developer Edition 124.0b9 (64-bit).

**Comment by safak45xx** [comment]
![Ekran Resmi 2024-03-13 18 27 56](https://github.com/safak45xx/Blurfox-MacOS-/assets/141409983/715120a3-6108-42ef-a377-0e4317a89a40)

**Comment by depleur** [comment]
Ah I see. I'd read this earlier, but didn't fully understand its functionality. Thanks, will check it out!

**Comment by depleur** [comment]
This works perfectly. Thanks for the help!
