### ISSUE TITLE
Outlook.com Font Issue

### ISSUE THREAD

**Issue by TwisterMc** [safak45xx/Blurfox-MacOS-#5]
The way the CSS is written, it's breaking icons on Outlook.com.

![SCR-20240221-hvsx](https://github.com/safak45xx/Blurfox-MacOS-/assets/46997/d926053a-441d-4c6b-b0bb-cfc15a77bd3c)

This can be fixed by disabling

```
* {
-moz-osx-font-smoothing:auto !important;
 font-family: -apple-system, system-ui, BlinkMacSystemFont !important;
   scrollbar-width: none !important;
   }
```

and 

```
* {
-moz-osx-font-smoothing:auto !important;
 font-family: -apple-system, system-ui, BlinkMacSystemFont !important;
   scrollbar-width: none !important;
   }
```

If you want to keep custom fonts, we'll need to find a way to target specific elements, and not `*`.

**Comment by safak45xx** [comment]
![Ekran Resmi 2024-02-21 18 07 53](https://github.com/safak45xx/Blurfox-MacOS-/assets/141409983/075096f3-f6e0-4c09-9b87-c954c78e6b50)

**Comment by safak45xx** [comment]
I have a request from you
