### ISSUE TITLE
Where is the css?

### ISSUE THREAD

**Issue by Bali10050** [safak45xx/Blurfox-MacOS-#6]
![Screen Shot 2024-02-24 at 14 54 59](https://github.com/safak45xx/Blurfox-MacOS-/assets/110120798/5d1f7568-3376-4aa5-a9a5-a2a16d696150)

**Comment by safak45xx** [comment]
![Ekran Resmi 2024-02-24 17 53 16](https://github.com/safak45xx/Blurfox-MacOS-/assets/141409983/18a38df5-eae9-4b9a-b506-396cc96260f3)
https://github.com/safak45xx/Blurfox-MacOS-/releases

**Comment by Bali10050** [comment]
`git clone https://github.com/safak45xx/Blurfox-MacOS-` will only get you those two files, and only providing releases destroys the porpuse of doing this project in git

**Comment by safak45xx** [comment]
I'm new to GitHub and I don't have much knowledge, so I haven't uploaded the files.

**Comment by safak45xx** [comment]
Such a method is easier for me.
