### ISSUE TITLE
Sure, I need your help for the cover design.

### ISSUE THREAD

**Issue by safak45xx** [safak45xx/Blurfox-MacOS-#7]
![Ekran Resmi 2024-02-25 19 33 35](https://github.com/safak45xx/Blurfox-MacOS-/assets/141409983/e6b99eb8-b088-4663-bbd3-f229a586c487)
I'm not good at design. Is there anyone who can create a cover design similar to this?

**Comment by drkhero** [comment]
why did you take down the whole theme?

**Comment by safak45xx** [comment]
> why did you take down the whole theme?

https://github.com/safak45xx/Blurfox-MacOS-/releases/tag/0.4.4
